version: '3.7'

services:

  movies-admin:
    build:
      context: ./DjangoMovieAdmin
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py migrate
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/DjangoMovieAdmin/movies-admin/config/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./DjangoMovieAdmin/.env.django
    depends_on:
      - db
  
        
  db:
    build:
      context: .
      dockerfile: Dockerfiledb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - 5432:5432
      
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch/data/
    env_file:
      - .env.es
    ports:
      - 9200:9200
      
      
  sqlite-to-postgres:
    build: 
      context: ./sqlite_to_postgres
      dockerfile: Dockerfile
    command: python ./main.py
    env_file:
      - ./sqlite_to_postgres/.env.sqlite_pg
    depends_on:
      - db
      - movies-admin
     
      
  postgres-to-elastic:
    build: 
      context: ./postgres_to_elastic
      dockerfile: Dockerfile
    command: python ./main.py
    env_file:
      - ./postgres_to_elastic/.env.pg_es
    depends_on:
      - sqlite-to-postgres
 
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/DjangoMovieAdmin/movies-admin/config/staticfiles
    ports:
      - 1337:80
    depends_on:
      - movies-admin

      
volumes:
  postgres_data:
  elasticsearch_data:
  static_volume:

